@Library('ProductionLineTemplateLib')

import com.capgemini.productionline.configuration.JenkinsConfiguration;

JenkinsConfiguration jenkinsConfiguration = new JenkinsConfiguration(this);

pipeline {
    agent any

    parameters {
        string(name: 'plugin_download_url', defaultValue: '', description: 'Download URL for the plugin to install', trim: true)
    }


    stages {
        stage('Download & install the plugin') {
            steps {
                script {
                    sh "wget ${params.plugin_download_url}"
                    sh "mv *.jar /pl_component_mounts/sonarqube/sonarqube_ext/plugins/"
                }
            }
        }
    }
}